#ifndef __THE_RENDER_BUFFER_H__
#define __THE_RENDER_BUFFER_H__

#include <stdint.h>

typedef enum
{
	THE_BT_NONE = 0,
	THE_BT_VERTEX_BUFFER_3P,
	THE_BT_VERTEX_BUFFER_3P_3N,
	THE_BT_VERTEX_BUFFER_3P_2UV,
	THE_BT_VERTEX_BUFFER_3P_3N_2UV,
	THE_BT_VERTEX_BUFFER_3P_3N_3T_3B_2UV,
	THE_BT_INDEX_BUFFER,
} THE_BufferType;



#endif